config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  namespace :clients do
    resources :questions, only: %i[index new create show] do
      member do
        post 'answers/:answer_id', to: 'questions#approve_answer_payment',
                                   as: :approve_answer_payment
      end
    end
  end

  namespace :lawyers do
    resources :questions, only: [:index] do
      collection do
        get :answered
      end
      resources :answers, only: %i[new create] do
        collection do
          get :view
        end
      end
    end
  end

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
  end

  devise_scope :user do
    authenticated :user, lambda(&:admin?) do
      root to: 'admin/dashboard#index', as: :admin_root
    end

    authenticated :user, lambda(&:lawyer?) do
      root to: 'lawyers/questions#index', as: :lawyer_root
    end

    authenticated :user, lambda(&:client?) do
      root to: 'clients/questions#index', as: :client_root
    end
  end

  root to: 'clients/questions#index'
end

app/models/answer.rb
# frozen_string_literal: true

# :nodoc:
class Answer < ApplicationRecord
  include Loggable
  belongs_to :question
  belongs_to :user

  validates :response_text, presence: true
  validates :proposed_fee, presence: true

  scope :paid, -> { where(paid: true) }

  after_create :generate_payment_request

  def approved_payment
    update(paid: true)
    question.update(status: 'answered') if question.status == 'open'

    log_info("User #{question.user.name} approved payment of £#{proposed_fee} for answer ##{id}")
  end

  private

  def generate_payment_request
    PaymentRequestService.new(self).call
  end
end

app/models/application_record.rb
# frozen_string_literal: true

# :nodoc:
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/loggable.rb
# frozen_string_literal: true

# :nodoc:
module Loggable
  def log_info(message)
    Rails.logger.info ":::#{message}:::"
  end
end

app/models/question.rb
# frozen_string_literal: true

# :nodoc:
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers

  validates :title, presence: true
  validates :body, presence: true
  validates :category, presence: true

  enum :status, { open: 0, answered: 1, closed: 2 }
  scope :open, -> { where(status: 'open') }

  before_validation :set_default_status, on: :create

  private

  def set_default_status
    self.status ||= :open
  end
end

app/models/user.rb
# frozen_string_literal: true

# :nodoc:
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions
  has_many :answers

  enum :role, { admin: 0, lawyer: 1, client: 2 }

  after_initialize :set_default_role, if: :new_record?

  private

  def set_default_role
    self.role ||= :client
  end
end

app/controllers/admin/base_controller.rb
# frozen_string_literal: true

module Admin
  # :nodoc:
  class BaseController < ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin
    layout 'user'

    private

    def authenticate_admin
      redirect_to root_path unless current_user.admin?
    end
  end
end

app/controllers/admin/dashboard_controller.rb
# frozen_string_literal: true

module Admin
  # Admin dashboard
  class DashboardController < BaseController
    def index
      @paid_answer = Answer.paid
      @paid_answers_count = @paid_answer.count
      @simulated_revenue = @paid_answer.sum(:proposed_fee)
      @open_que_count = Question.open.count
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# :nodoc:
class ApplicationController < ActionController::Base
  include Pagy::Backend
  add_flash_types :info, :error, :success
  allow_browser versions: :modern
  protect_from_forgery with: :exception
end

app/controllers/clients/base_controller.rb
# frozen_string_literal: true

module Clients
  # :nodoc:
  class BaseController < ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_client
    layout 'user'

    private

    def authenticate_client
      redirect_to root_path unless current_user.client?
    end
  end
end

app/controllers/clients/questions_controller.rb
# frozen_string_literal: true

module Clients
  # Client Questions
  class QuestionsController < BaseController
    before_action :set_question, only: %i[show approve_answer_payment]

    def index
      @pagy, @questions = pagy_countless(
        current_user.questions
                    .includes(:answers)
                    .order(created_at: :desc)
      )
      respond_to do |format|
        format.html
        format.turbo_stream
      end
    end

    def new
      @question = current_user.questions.build
    end

    def create
      @question = current_user.questions.build(question_params)

      if @question.save
        flash[:success] = 'Question Created Succssfully.'
        redirect_to clients_questions_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def show
      @answers = @question.answers
    end

    def approve_answer_payment
      @answer = @question.answers.find(params[:answer_id])
      @answer.approved_payment

      respond_to do |format|
        format.turbo_stream
        format.html do
          redirect_to clients_question_path(@question),
                      notice: 'Payment approved. You can now view the answer.'
        end
      end
    end

    private

    def question_params
      params.require(:question).permit(:title, :body, :category)
    end

    def set_question
      if current_user.questions.present?
        @question = current_user.questions.find_by_id(params[:id])
        redirect_to root_path unless @question
      else
        redirect_to root_path
      end
    end
  end
end

app/controllers/lawyers/answers_controller.rb
# frozen_string_literal: true

module Lawyers
  # Lawyers Answers
  class AnswersController < BaseController
    before_action :set_question, only: %i[new create view]
    before_action :verify_question_status, only: %i[create]

    def new
      @answer = current_user.answers.build
    end

    def create
      @answer = current_user.answers.build(answer_params)
      @answer.question = @question

      if @answer.save
        flash[:success] = 'Simulated payment request sent.'
        redirect_to lawyers_questions_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def view
      @answers = current_user.answers.where(question_id: @question.id)
    end

    private

    def set_question
      @question = Question.find(params[:question_id])
    end

    def verify_question_status
      redirect_to lawyers_questions_path unless @question.open?
    end

    def answer_params
      params.require(:answer).permit(:response_text, :proposed_fee)
    end
  end
end

app/controllers/lawyers/base_controller.rb
# frozen_string_literal: true

module Lawyers
  # :nodoc:
  class BaseController < ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_lawyer
    layout 'user'

    private

    def authenticate_lawyer
      redirect_to root_path unless current_user.lawyer?
    end
  end
end

app/controllers/lawyers/questions_controller.rb
# frozen_string_literal: true

module Lawyers
  # Lawyers Questions
  class QuestionsController < BaseController
    def index
      @pagy, @questions = pagy(Question.open.order(created_at: :desc))
    end

    def answered
      @pagy, @questions = pagy(AnsweredQuestionsService.new(current_user).call)
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  # :nodoc:
  class RegistrationsController < Devise::RegistrationsController
    def create
      build_resource(registration_params)
      if resource.save
        redirect_to new_user_session_path
      else
        flash[:alert] = 'Please fill correct data.'
        respond_with resource, location: new_user_registration_path
      end
    end

    private

    def registration_params
      params.require(:user).permit(
        :name, :email, :password, :password_confirmation
      )
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  # :nodoc:
  class SessionsController < Devise::SessionsController
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# :nodoc:
module ApplicationHelper
  include Pagy::Frontend
end

app/views/admin/dashboard/index.html.haml
%h1 Admin Dashboard
.card.m-2
  .card-body
    %h5.card-title Opened Questions
    %p.card-text= @open_que_count
.card.m-2
  .card-body
    %h5.card-title Total Paid Answers
    %p.card-text= @paid_answers_count
.card.m-2
  .card-body
    %h5.card-title Simulated Revenue
    %p.card-text
      £#{@simulated_revenue}

app/views/clients/questions/_question.html.haml
.list-group-item
  %h5= link_to question.title, clients_question_path(question)
  %div= truncate(question.body, length: 150)
  %div
    %b Status: #{question.status.capitalize}
  %small.text-muted
    Category: #{question.category}
  - if question.answers.any? 
    %div
      %span.badge.badge-success Answers Available

app/views/clients/questions/_single_answer.html.haml
.mt-2.border.p-3.rounded
  - if current_user == question.user && answer.paid
    %p 
      = "Answer by Lawyer: #{answer.user.name}"
    %p
      %strong Advice:
      = answer.response_text
    %p.text-sm.text-gray-500
      Proposed Fee: £#{answer.proposed_fee}
  - else
    %p 
      = "Answer by Lawyer: #{answer.user.name}"
    %p.italic This answer is locked until payment is approved.
    = button_to "Approve Payment (£#{answer.proposed_fee})", approve_answer_payment_clients_question_path(question, answer), method: :post, class: "btn btn-primary btn-block"

app/views/clients/questions/approve_answer_payment.turbo_stream.haml
= turbo_stream.replace("status_answers_#{@question.id}", 'Answered')
= turbo_stream.replace("answer_#{@answer.id}", partial: 'single_answer', locals: { answer: @answer, question: @question })

app/views/clients/questions/index.html.haml
= link_to "Ask a Question", new_clients_question_path, class: 'btn btn-primary'
- if @questions.any?
  %h1.text-center.mb-4 Recent Questions
  #questions.list-group
    = render partial: "question", collection: @questions, as: :question
  - if @pagy.next.present?
    #next_link.mt-2
      = link_to "Load More", pagy_url_for(@pagy, @pagy.next), data: { turbo_stream: true }, class: 'btn btn-primary'       
- else
  %h3.text-center.mb-4 No questions at the moment.

app/views/clients/questions/index.turbo_stream.haml
= turbo_stream.append "questions" do
  = render partial: "question", collection: @questions, as: :question
= turbo_stream.update "next_link" do
  - if @pagy.next.present?
    = link_to "Load More", pagy_url_for(@pagy, @pagy.next), data: { turbo_stream: true }, class: 'btn btn-primary'       
    

app/views/clients/questions/new.html.haml
%h1 Ask a Legal Question
= form_with model: [:clients, @question], data: {turbo: false} do |f|
  .mt-2
    = f.label :title
    = f.text_field :title, class: "form-control", required: true
  .mt-2
    = f.label :body, "Question Details"
    = f.text_area :body, rows: 6, class: "form-control", required: true
  .mt-2
    = f.label :category
    = f.select :category, ['Family Law', 'Property', 'Wills & Probate', 'Employment', 'Other'], {}, class: "form-control"
  .mt-2
    = f.submit "Submit Question", class: "btn btn-primary btn-block"
.mt-2
  = link_to "Back to My Questions", clients_questions_path, class: 'btn btn-primary'

app/views/clients/questions/show.html.haml
%div.mb-2{id: "answers_#{@question.id}"}
  = render 'common/question_details', question: @question
  - if @answers.any?
    - @answers.each do |a|
      %div.mb-2{id: "answer_#{a.id}"}
        = render 'single_answer', answer: a, question: @question
  - else
    %h5 There is no answer yet.
.mt-2
  = link_to "Back to Questions", clients_questions_path, class: 'btn btn-primary'

app/views/common/_answer_list.html.haml
.list-group
  - answers.each do |answer|
    .list-group-item
      - if answer.user == current_user && answer.paid?
        %div
          %span.badge.badge-success Paid by #{question.user.name}
      - if (current_user == question.user && answer.paid) || answer.user == current_user
        %p
          %strong Advice:
          = answer.response_text
        %small.text-muted
          Proposed fee: #{answer.proposed_fee} 
      - else
        %p.italic This answer is locked until payment is approved.
        = button_to "Approve Payment (£#{answer.proposed_fee})", approve_answer_payment_clients_question_path(question, answer), method: :post, class: "btn btn-primary btn-block"

app/views/common/_question_details.html.haml
%h3
  %strong Que:
  = question.title
%div
  %strong Category:
  = question.category
%div
  %strong Status:
  %span{id: "status_answers_#{@question.id}"}
    = question.status.capitalize
%label
  %strong Description:
%div
  = question.body

app/views/lawyers/answers/new.html.haml
= render 'common/question_details', question: @question
= form_with model: [:lawyers, @question, @answer] do |f|
  .mt-2
    = f.label :response_text, "Your Legal Advice"
    = f.text_area :response_text, rows: 6, class: 'form-control', required: true
  .mt-2
    = f.label :proposed_fee, "Proposed Fee (£)"
    = f.number_field :proposed_fee, step: 1.0, class: 'form-control', required: true
  .mt-2
    = f.submit "Submit Answer", class: 'btn btn-primary btn-block'
.mt-2
  = link_to "View Open Questions", lawyers_questions_path, class: 'btn btn-primary'

app/views/lawyers/answers/view.html.haml
= render 'common/question_details', question: @question
- if @answers.any?
  = render 'common/answer_list', answers: @answers, question: @question
- else
  %h5 You have not answered this question.
- if @question.open?
  .mt-2
    = link_to "Answer", new_lawyers_question_answer_path(@question), class: 'btn btn-primary'
.mt-2
  = link_to "View Open Questions", lawyers_questions_path, class: 'btn btn-primary'

app/views/lawyers/questions/_list.html.haml
.list-group
  - questions.each do |question|
    .list-group-item
      %h5= link_to question.title, view_lawyers_question_answers_path(question)
      %div= truncate(question.body, length: 150)
      %div
        %b Status: #{question.status.capitalize}
      %small.text-muted
        Category: #{question.category}
      .mt-2
        - if question.open?
          = link_to "Answer", new_lawyers_question_answer_path(question), class: 'btn btn-primary'

app/views/lawyers/questions/answered.html.haml
= link_to "View Open Questions", lawyers_questions_path, class: 'btn btn-primary'
%h1.text-center.mb-4 Your Answered Questions
- if @questions.any?
  = render 'list', questions: @questions
  .d-flex.justify-content-center.mt-2
    != pagy_bootstrap_nav(@pagy) if @pagy.pages > 1
- else
  %h5 No Answered questions at the moment.

app/views/lawyers/questions/index.html.haml
= link_to "Answered Questions", answered_lawyers_questions_path, class: 'btn btn-primary'
%h1.text-center.mb-4 Open Legal Questions
- if @questions.any?
  = render 'list', questions: @questions
  .d-flex.justify-content-center.mt-2
    != pagy_bootstrap_nav(@pagy) if @pagy.pages > 1
- else
  %h5 No open questions at the moment.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Legal Qa Board"
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    %meta{content: "yes", name: "apple-mobile-web-app-capable"}/
    %meta{content: "yes", name: "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{href: "/icon.png", rel: "icon", type: "image/png"}/
    %link{href: "/icon.svg", rel: "icon", type: "image/svg+xml"}/
    %link{href: "/icon.png", rel: "apple-touch-icon"}/
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    %link{href: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css", rel: "stylesheet"}/
    %link{href: "https://mdbcdn.b-cdn.net/wp-content/themes/mdbootstrap4/docs-app/css/dist/mdb5/standard/core.min.css", rel: "stylesheet"}/
    %link{href: "https://mdbcdn.b-cdn.net/wp-content/themes/mdbootstrap4/docs-app/css/mdb5/fonts/roboto-subset.css?ver=3.9.0-update.5", id: "roboto-subset.css-css", media: "all", rel: "stylesheet", type: "text/css"}/
    = javascript_importmap_tags
  %body
  .container.mx-auto.p-4
    .mt-8
      = yield

app/views/layouts/user.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Legal Qa Board"
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    %meta{content: "yes", name: "apple-mobile-web-app-capable"}/
    %meta{content: "yes", name: "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{href: "/icon.png", rel: "icon", type: "image/png"}/
    %link{href: "/icon.svg", rel: "icon", type: "image/svg+xml"}/
    %link{href: "/icon.png", rel: "apple-touch-icon"}/
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    %link{href: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css", rel: "stylesheet"}/
    %link{href: "https://mdbcdn.b-cdn.net/wp-content/themes/mdbootstrap4/docs-app/css/dist/mdb5/standard/core.min.css", rel: "stylesheet"}/
    %link{href: "https://mdbcdn.b-cdn.net/wp-content/themes/mdbootstrap4/docs-app/css/mdb5/fonts/roboto-subset.css?ver=3.9.0-update.5", id: "roboto-subset.css-css", media: "all", rel: "stylesheet", type: "text/css"}/
    = javascript_importmap_tags
  %body
    .layout-wrapper.layout-content-navbar
      .layout-container
        .layout-page
          = render 'shared/navbar'
          .content-wrapper
            .container-xxl.flex-grow-1.container-p-y
              .mt-5
                = render 'shared/notification'
                = yield

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.bg-body-tertiary          
  .container-fluid
    #navbarSupportedContent.collapse.navbar-collapse
      %h5
        Logged In #{current_user.role} : #{current_user.name}
    .d-flex.align-items-center
      = link_to "Sign Out", destroy_user_session_path, class: "text-blue-600 underline", data: { "turbo-method": :delete }

app/views/shared/_notification.html.haml
- flash.each do |type, msg|
  - if notice
    .alert.alert-info.alert-dismissible.fade.show.m-1{role: "alert"}
      = msg
  - if alert
    .alert.alert-warning.alert-dismissible.fade.show.m-1{role: "alert"}
      = msg
  - if success
    .alert.alert-success.alert-dismissible.fade.show.m-1{role: "alert"}
      = msg

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>